### PR TITLE
YubiKey plugin

### PR DESCRIPTION
**Pull request by str4d**
### Current draft specification:

https://hackmd.io/@str4d/age-plugin-yubikey

### CODE REVIEW

**Comment by joonas-fi** [comment]
Adding my 5 cents: I would not call it "A YubiKey stanza", but instead "P-256" and not even tie it to PIV (= smartcard stuff), because all of the operations are:

- something that can be done in another manufacturer's PIV implementation
- or even in a software smartcard implementation
- or even outside of PIV context. It's just P-256
- the plugin itself is fine being scoped to YubiKey-stored P-256. I'd just decouple the Age stanza and YubiKey from each other.

**Comment by joonas-fi** [comment]
> where SEC-1-C is the 33-byte compressed SEC-1 encoding.

FYI in case you're not aware, if "compressed encoding" means omitting the `y` coordinate, it needs to be re-computed from `x` and it seems to be pretty expensive: https://twitter.com/joonas_fi/status/1318829182743359489

**Comment by str4d** [comment]
Now that (unstable) plugin support is merged into `rage` (https://github.com/str4d/rage/pull/99), I'll be working on this PR again!

@joonas-fi The stanza tag used in the header is going to end up named something like `piv-p256`, since (as you note) it's not tied to YubiKey specifically (though it _is_ tied to a specific 

The cost of decompression only needs to be paid at recipient parsing time, and we gain more benefit from having shorter recipient strings. I think the current implementation might end up decompressing once per wrapped stanza, but that's easy to fix if it actually proves to be a bottleneck (vs the actual file encryption).

**Comment by jstasiak** [comment]
I tested this with YubiKey 4 on Mac and it's working very nicely! The only issue I found is I need to enter PIN on every decryption even though the PIN policy has been set to "once" (?).

I opened a PR (#3) to address a use case that's important to me (first mentioned here: https://github.com/str4d/rage/pull/25#issuecomment-577264766).

**Comment by str4d** [comment]
Hi, thanks for testing! Just FYI, I reworked this branch on a recent Twitch stream, and will shortly be opening new PRs with the improved plugin implementation.

Re: always needing a PIN, that's an artifact of plugins being started fresh each time rage runs. This is intentional; plugins are short-lived. The reason I offer a Once policy is because it _will_ be used by an agent plugin. The expectation is that yubikey-agent will add support for this recipient type, and then this plugin will be used for encryption, while the agent can be used for decryption if the user desires.

**Comment by jstasiak** [comment]
Cool, I'll update my branch when you post your changes. Fair enough on the PIN prompts, I somehow thought the device kept track of PIN entries and it wasn't per-session.

**Comment by str4d** [comment]
PIN entries are only cached per-connection to the YubiKey, so decrypting multiple files with the same YubiKey _would_ leverage a Once policy correctly (not that `age` or `rage` support that use-case, but the plugin system does), but you need some process holding that connection open (and in doing so, holding a lock on the YubiKey) if you want it to last beyond a single plugin invocation.

**Comment by jstasiak** [comment]
Thanks, that's what I figured. You mentioned yubikey-agent, is it about this one? https://github.com/FiloSottile/yubikey-agent If there was a single agent that'd serve both my SSH and (r)age needs it'd be glorious.

**Comment by jstasiak** [comment]
> The expectation is that yubikey-agent will add support for this recipient type, and then this plugin will be used for encryption, while the agent can be used for decryption if the user desires.

One more question about this: would this reuse the SSH agent protocol and extend it to support decryption or provide a separate protocol for (r)age? Is there an existing discussion of this yubikey-agent extension? I've played around with sshcrypt[1] and yubikey-agent (a version modified by me to get deterministic RSA signatures working instead of ECDSA signatures which are randomized) to get encryption and decryption using SSH keys with agent support but it has a range of downsides (like: encryption requires SSH sign operation with a touch action and requiring signature to encrypt means a third party can't encrypt stuff to me). I had an idea for an age plugin that implements something like that using SSH agent but it'd have the same set of downsides which is a showstopper for me.


[1] https://github.com/leighmcculloch/sshcrypt

**Comment by str4d** [comment]
Replaced by #8.

**Comment by str4d** [comment]
> One more question about this: would this reuse the SSH agent protocol and extend it to support decryption or provide a separate protocol for (r)age? Is there an existing discussion of this yubikey-agent extension?

The existing discussion is mostly in @FiloSottile's Twitch streams IIRC, along with he and I chatting about it. I suspect it will be a protocol specific to `yubikey-agent`, i.e. `yubikey-agent` would speak the SSH agent protocol for SSH usage, and then have its own protocol between its short-lived plugin binary and its long-lived agent. Let's shift that conversation over to `yubikey-agent`.

**Pull request closed without merging**
