### PR TITLE
fix: ignore non-functional smartcard readers

### LINKED ISSUE #81: Smart card reader is not being ignored by `--list`, `--list-all` when no card inserted
## What were you trying to do
I was trying to use `age-plugin-yubikey`.

### Short
I am getting the following error:

```
age-plugin-yubikey --list-all

Error: Error while communicating with YubiKey: PC/SC error
Cause: The operation requires a Smart Card, but no Smart Card is currently in the device

[ Did this not do what you expected? Could an error be more useful? ]
[ Tell us: https://str4d.xyz/age-plugin-yubikey/report              ]
```

and I don't know where to go from here.
It would be nice to have a beginner's guide section for people that aren't familiar with PIV and get here because they know age and happen to have a yubikey laying around for other things (FIDO for example)

### Longer
Thank you for developing this plugin!
I got here because I am familiarizing myself with age/rage and using it for various tasks.
As I also own a yubikey, I thought it would be interesting to combine it with age and check this plugin out.
But, I am not at all familiar with PIV/smart cards, and it is a bit daunting to understand how to put the pieces together.
I think that yubico could make more effort to make it easier to introduce the PIV features, but I also guess that most people know what they are doing when getting a key as a smart card replacement.
So maybe I am just an odd duck in this case :D 

It would be helpful if the README could link to relevant resources to familiarize beginners with PIV and that additional functionality.
Especially a way to test that everything _else_ works before starting `age-plugin-yubikey`, as I assume that I have some other issues and that it isn't the plugin's fault.
That is my main request for the issue :) 

To provide some additional information for my error message: If I run `pcsc_scan` the yubikey is detected and identified as a smart card.

### PR DESCRIPTION
**Pull request by michaeladler**
Hi,

first of all thanks for this great plugin! This MR fixes #81 and contains another non-obvious fix:

I noticed that we connect *twice* to the reader because `key::filter_connected`
already opens a connection - which we then don't use. First of all, it's not
necessary to check for connected readers because the subsequent
`open_connection` will fail anyway and we just skip it. **More importantly, it
seems that the connection created using filter_connected invalidates the pin
session** because it's not closed using `disconnect_without_reset`.

### CODE REVIEW

**Comment by str4d** [comment]
> More importantly, it seems that the connection created using `filter_connected` invalidates the pin session because it's not closed using `disconnect_without_reset`.

Good catch! I suspect this is the root cause of the recent "PIN is reset when I didn't expect it to be" issues, because `filter_connected` is reachable from `--generate`, `--list`, `--identity`, and the TUI. I've opened #116 to fix this (along with a related bug I found).

**Comment by str4d** [comment]
Re: this PR, while this PR does technically fix #81, it also hides a bunch of unrelated errors that I would prefer be reported to the user (and subsequently to me). I believe I've identified the underlying issue and fixed it in #117; could you test it, if #81 was affecting you?

**Comment by michaeladler** [comment]
Hi,

I've tested #117 but it still resets the PIN, likely because the other smartcard (not a Yubikey) causes an error:

```bash
$ age-plugin-yubikey -l
#       Serial: XXXXXXXX, Slot: 1
#         Name: age identity 00000000
#      Created: Mon, 23 Jan 2023 16:01:09 +0000
#   PIN policy: Once   (A PIN is required once per session, if set)
# Touch policy: Always (A physical touch is required for every decryption)
age1yubikey000000000000000000000000000000000000000000000000000000000000


Error: Error while communicating with YubiKey: generic error

[ Did this not do what you expected? Could an error be more useful? ]
[ Tell us: https://str4d.xyz/age-plugin-yubikey/report              ] 
```

**Comment by str4d** [comment]
Could you rerun with `RUST_LOG=trace` and see what it returns? Replacing the "generic error"s with more specific ones in the `yubikey` create is on my to-do list, but sometimes they just arise from `pcsc` so the APDU trace might be necessary.

**Comment by michaeladler** [comment]
Sure, here's the logging output:

[stderr.log](https://github.com/str4d/age-plugin-yubikey/files/10536472/stderr.log)

**Comment by str4d** [comment]
Regarding the PIN still resetting, that is expected for #117 because that PR is targeting version 0.3.3, and doesn't include the PIN reset avoidance logic which will be in version 0.4.0.

Regarding smart card readers being ignored, AFAICT your trace log indicates this is working, and that we _also_ need to treat "PIV applet not found" errors as an indicator for ignoring a smart card. The latter I can't do until 0.4.0 because it needs changes in `yubikey`, but I'm going to go ahead and merge #117 in the meantime.

**Comment by michaeladler** [comment]
Sounds good! I guess this MR is superseded by #117 and can be closed then. Just ping me if there is anything you want me to regarding these smart card error issues.

**Pull request closed without merging**
